fix: mongodb replica set config fixed

diff --git a/.devcontainer/docker-compose.yml b/.devcontainer/docker-compose.yml
--- a/.devcontainer/docker-compose.yml
+++ b/.devcontainer/docker-compose.yml
@@ -23,9 +23,10 @@ services:
       - db_network
     command: tail -f /dev/null
     depends_on:
-      - mongodb
-      - neo4j
-      - mongo-init
+      mongoinit:
+        condition: service_completed_successfully
+      neo4j:
+        condition: service_started
 
   mongodb:
     image: mongo:latest
@@ -37,24 +38,40 @@ services:
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
     volumes:
       - mongodb_data:/data/db
-      - ./mongo-init-config/keyfile:/etc/mongo-keyfile
-
-    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--auth", "--keyFile", "/etc/mongo-keyfile"]
     networks:
       - db_network
-
-  mongo-init:
-    image: mongo:latest
-    container_name: mongodb-init
-    depends_on:
-      - mongodb
-    entrypoint: >
+    command: |
       bash -c "
-        sleep 10 &&
-        mongosh --host mongodb --username admin --password admin --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongodb:27017\"}]})'
+      echo 'Generando keyfile...';
+      mkdir -p /etc/mongo-keyfile && openssl rand -base64 756 > /etc/mongo-keyfile/keyfile;
+      chmod 600 /etc/mongo-keyfile/keyfile;
+      chown mongodb:mongodb /etc/mongo-keyfile/keyfile;
+      if [ ! -s /etc/mongo-keyfile/keyfile ]; then
+        echo '❌ Error: El archivo keyfile no se generó correctamente.';
+        exit 1;
+      fi;
+      echo '✅ Keyfile generado correctamente.';
+      ls -l /etc/mongo-keyfile;
+      exec docker-entrypoint.sh mongod --replSet ${MONGO_REPLICA_SET:-rs0} --keyFile /etc/mongo-keyfile/keyfile --bind_ip_all
       "
+    healthcheck:
+      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
+      interval: 10s
+      timeout: 5s
+      retries: 5
+
+  mongoinit:
+    image: mongo:latest
+    container_name: mongoinit
+    restart: "no"
     networks:
       - db_network
+    depends_on:
+      mongodb:
+        condition: service_healthy
+    command: > 
+      bash -c "echo 'Esperando MongoDB...'; until mongosh --host ${MONGO_HOST:-mongodb} --port ${MONGO_PORT:-27017} --username ${MONGO_USER:-admin} --password ${MONGO_PASSWORD:-admin} --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'; do echo -n '.'; sleep 1; done; echo '✅ MongoDB listo'; mongosh --host ${MONGO_HOST:-mongodb}:${MONGO_PORT:-27017} --username ${MONGO_USER:-admin} --password ${MONGO_PASSWORD:-admin} --authenticationDatabase admin --eval \"try { rs.initiate({ _id: '${MONGO_REPLICA_SET:-rs0}', members: [ { _id: 0, host: '${MONGO_HOST:-mongodb}:${MONGO_PORT:-27017}' } ] }); print('✅ Replica set iniciado.'); } catch(e) { if (e.codeName=='AlreadyInitialized') print('ℹ️ Replica set ya estaba iniciado.'); else { print('❌ Error iniciando replica set:', e.message); throw e; } }\""
+
 
   neo4j:
     image: neo4j:latest
